version: '2'
services:
  app:
    build:
      context: app
    volumes:
      - ./app:/app
    ports:
      - "8002:8002"
    environment:
      - FLUENT_HOST=fluent
    links:
      - fluent

  fluent:
    build:
      context: fluent
    ports:
      - "24224:24224"
